name: CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**/*.md'

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: "Set up Node.js"
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install dependencies
              run: yarn install --frozen-lockfile --ignore-optional --non-interactive

            - name: Run yarn build
              run: yarn build
            - name: Get next version
              uses: reecetech/version-increment@2023.9.3
              id: version
              with:
                scheme: semver
                increment: patch
            - name: Set version
              run: echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                tag_name: ${{ steps.version.outputs.version }}
                release_name: Release ${{ steps.version.outputs.version }}
                draft: false
                prerelease: false
            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ./config-server.exe
                  asset_name: config-server.exe
                  tag: ${{ steps.version.outputs.version }}
                  overwrite: true
            - name: Delete previous release
              uses: dev-drprasad/delete-older-releases@v0.3.3
              with:
                  keep_latest: 1         
                  delete_tags: true  