name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: "Set up Node.js"
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install dependencies
              run: yarn install

            - name: Run yarn pkg
              run: yarn pkg
            - name: Create an incremental release
              uses: aurestic/incrementarl-create-release@master
              with:
                flag_branch: true
                message: Bump version
                prev_tag: 'v'
                update_odoo_module_version: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}