name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: "Set up Node.js"
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install dependencies
              run: yarn install

            - name: Run yarn pkg
              run: yarn pkg
            - name: Create Release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}